.

diff --git a/aws-quickstart b/aws-quickstart
--- a/aws-quickstart
+++ b/aws-quickstart
@@ -40,7 +40,7 @@ OPTIONS:
             Destroy the workload and infrastructure.
 
     --kubernetes-version
-            Kubernetes version to use.  This must be one of: 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.30, 1.31
+            Kubernetes version to use.  This must be one of: 1.25, 1.26, 1.27, 1.28, 1.29, 1.30, 1.31
             (default: 1.31).
 EOF
 }
@@ -101,15 +101,14 @@ if [ -z "${BASTION_REMOTE_ACCESS_CIDR_BLOCKS:-}" ] && [ -z "$DESTROY" ]; then
   ERROR=1
 fi
 
-if [ "${KUBERNETES_VERSION}" != "1.24" ] &&
-   [ "${KUBERNETES_VERSION}" != "1.25" ] &&
+if [ "${KUBERNETES_VERSION}" != "1.25" ] &&
    [ "${KUBERNETES_VERSION}" != "1.26" ] &&
    [ "${KUBERNETES_VERSION}" != "1.27" ] &&
    [ "${KUBERNETES_VERSION}" != "1.28" ] &&
    [ "${KUBERNETES_VERSION}" != "1.29" ] &&
    [ "${KUBERNETES_VERSION}" != "1.30" ] &&
    [ "${KUBERNETES_VERSION}" != "1.31" ]; then
-    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.30, 1.31"
+    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.25, 1.26, 1.27, 1.28, 1.29, 1.30, 1.31"
     ERROR=1
 fi
 
