done

diff --git a/aws-quickstart b/aws-quickstart
--- a/aws-quickstart
+++ b/aws-quickstart
@@ -40,15 +40,15 @@ OPTIONS:
             Destroy the workload and infrastructure.
 
     --kubernetes-version
-            Kubernetes version to use.  This must be one of: 1.26, 1.27, 1.28, 1.29, 1.30, 1.31, 1.32
-            (default: 1.32).
+            Kubernetes version to use.  This must be one of: 1.26, 1.27, 1.28, 1.29, 1.30, 1.31, 1.32, 1.33
+            (default: 1.33).
 EOF
 }
 
 # Default arguments.
 AMI_ID=""
 DESTROY=""
-KUBERNETES_VERSION="1.32"
+KUBERNETES_VERSION="1.33"
 XR_USERNAME=""
 XR_PASSWORD=""
 BASTION_REMOTE_ACCESS_CIDR_BLOCKS=""
@@ -107,8 +107,9 @@ if [ "${KUBERNETES_VERSION}" != "1.26" ] &&
    [ "${KUBERNETES_VERSION}" != "1.29" ] &&
    [ "${KUBERNETES_VERSION}" != "1.30" ] &&
    [ "${KUBERNETES_VERSION}" != "1.31" ] &&
-   [ "${KUBERNETES_VERSION}" != "1.32" ]; then
-    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.26, 1.27, 1.28, 1.29, 1.30, 1.31, 1.32"
+   [ "${KUBERNETES_VERSION}" != "1.32" ] &&
+   [ "${KUBERNETES_VERSION}" != "1.33" ]; then
+    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.26, 1.27, 1.28, 1.29, 1.30, 1.31, 1.32, 1.33"
     ERROR=1
 fi
 
