Add support for EKS v1.29 (#15)

diff --git a/aws-quickstart b/aws-quickstart
--- a/aws-quickstart
+++ b/aws-quickstart
@@ -37,15 +37,15 @@ OPTIONS:
             Destroy the workload and infrastructure.
 
     --kubernetes-version
-            Kubernetes version to use.  This must be one of: 1.23, 1.24, 1.25, 1.26, 1.27, 1.28
-            (default: 1.28).
+            Kubernetes version to use.  This must be one of: 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29
+            (default: 1.29).
 EOF
 }
 
 # Default arguments.
 AMI_ID=""
 DESTROY=""
-KUBERNETES_VERSION="1.28"
+KUBERNETES_VERSION="1.29"
 XR_USERNAME=""
 XR_PASSWORD=""
 
@@ -94,8 +94,9 @@ if [ "${KUBERNETES_VERSION}" != "1.23" ] &&
    [ "${KUBERNETES_VERSION}" != "1.25" ] &&
    [ "${KUBERNETES_VERSION}" != "1.26" ] &&
    [ "${KUBERNETES_VERSION}" != "1.27" ] &&
-   [ "${KUBERNETES_VERSION}" != "1.28" ]; then
-    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.23, 1.24, 1.25, 1.26, 1.27, 1.28"
+   [ "${KUBERNETES_VERSION}" != "1.28" ] &&
+   [ "${KUBERNETES_VERSION}" != "1.29" ]; then
+    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29"
     ERROR=1
 fi
 
