Updated all kubernetes versions

diff --git a/aws-quickstart b/aws-quickstart
--- a/aws-quickstart
+++ b/aws-quickstart
@@ -40,15 +40,15 @@ OPTIONS:
             Destroy the workload and infrastructure.
 
     --kubernetes-version
-            Kubernetes version to use.  This must be one of: 1.28, 1.29, 1.30, 1.31, 1.32, 1.33
-            (default: 1.33).
+            Kubernetes version to use.  This must be one of: 1.29, 1.30, 1.31, 1.32, 1.33, 1.34
+            (default: 1.34).
 EOF
 }
 
 # Default arguments.
 AMI_ID=""
 DESTROY=""
-KUBERNETES_VERSION="1.33"
+KUBERNETES_VERSION="1.34"
 XR_USERNAME=""
 XR_PASSWORD=""
 BASTION_REMOTE_ACCESS_CIDR_BLOCKS=""
@@ -101,13 +101,13 @@ if [ -z "${BASTION_REMOTE_ACCESS_CIDR_BLOCKS:-}" ] && [ -z "$DESTROY" ]; then
   ERROR=1
 fi
 
-if [ "${KUBERNETES_VERSION}" != "1.28" ] &&
-   [ "${KUBERNETES_VERSION}" != "1.29" ] &&
+if [ "${KUBERNETES_VERSION}" != "1.29" ] &&
    [ "${KUBERNETES_VERSION}" != "1.30" ] &&
    [ "${KUBERNETES_VERSION}" != "1.31" ] &&
    [ "${KUBERNETES_VERSION}" != "1.32" ] &&
-   [ "${KUBERNETES_VERSION}" != "1.33" ]; then
-    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.28, 1.29, 1.30, 1.31, 1.32, 1.33"
+   [ "${KUBERNETES_VERSION}" != "1.33" ] &&
+   [ "${KUBERNETES_VERSION}" != "1.34" ]; then
+    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.29, 1.30, 1.31, 1.32, 1.33, 1.34"
     ERROR=1
 fi
 
