Update files for eks 1.35 (#53)

diff --git a/aws-quickstart b/aws-quickstart
--- a/aws-quickstart
+++ b/aws-quickstart
@@ -40,15 +40,15 @@ OPTIONS:
             Destroy the workload and infrastructure.
 
     --kubernetes-version
-            Kubernetes version to use.  This must be one of: 1.29, 1.30, 1.31, 1.32, 1.33, 1.34
-            (default: 1.34).
+            Kubernetes version to use.  This must be one of: 1.29, 1.30, 1.31, 1.32, 1.33, 1.34, 1.35
+            (default: 1.35).
 EOF
 }
 
 # Default arguments.
 AMI_ID=""
 DESTROY=""
-KUBERNETES_VERSION="1.34"
+KUBERNETES_VERSION="1.35"
 XR_USERNAME=""
 XR_PASSWORD=""
 BASTION_REMOTE_ACCESS_CIDR_BLOCKS=""
@@ -106,8 +106,9 @@ if [ "${KUBERNETES_VERSION}" != "1.29" ] &&
    [ "${KUBERNETES_VERSION}" != "1.31" ] &&
    [ "${KUBERNETES_VERSION}" != "1.32" ] &&
    [ "${KUBERNETES_VERSION}" != "1.33" ] &&
-   [ "${KUBERNETES_VERSION}" != "1.34" ]; then
-    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.29, 1.30, 1.31, 1.32, 1.33, 1.34"
+   [ "${KUBERNETES_VERSION}" != "1.34" ] &&
+   [ "${KUBERNETES_VERSION}" != "1.35" ]; then
+    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.29, 1.30, 1.31, 1.32, 1.33, 1.34, 1.35"
     ERROR=1
 fi
 
