added 1.31 support (#25)

diff --git a/aws-quickstart b/aws-quickstart
--- a/aws-quickstart
+++ b/aws-quickstart
@@ -40,15 +40,15 @@ OPTIONS:
             Destroy the workload and infrastructure.
 
     --kubernetes-version
-            Kubernetes version to use.  This must be one of: 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.30
-            (default: 1.30).
+            Kubernetes version to use.  This must be one of: 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.30, 1.31
+            (default: 1.31).
 EOF
 }
 
 # Default arguments.
 AMI_ID=""
 DESTROY=""
-KUBERNETES_VERSION="1.30"
+KUBERNETES_VERSION="1.31"
 XR_USERNAME=""
 XR_PASSWORD=""
 BASTION_REMOTE_ACCESS_CIDR_BLOCKS=""
@@ -108,8 +108,9 @@ if [ "${KUBERNETES_VERSION}" != "1.23" ] &&
    [ "${KUBERNETES_VERSION}" != "1.27" ] &&
    [ "${KUBERNETES_VERSION}" != "1.28" ] &&
    [ "${KUBERNETES_VERSION}" != "1.29" ] &&
-   [ "${KUBERNETES_VERSION}" != "1.30" ]; then
-    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.30"
+   [ "${KUBERNETES_VERSION}" != "1.30" ] &&
+   [ "${KUBERNETES_VERSION}" != "1.31" ]; then
+    >&2 echo "error: Kubernetes version (--kubernetes-version) must be one of: 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.30, 1.31"
     ERROR=1
 fi
 
